# Generated by Django 5.1.7 on 2025-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_alter_comment_created_at_alter_comment_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[('سلبي', 'سلبي'), ('حيادي', 'حيادي'), ('إيجابي', 'إيجابي')], max_length=10),
        ),
    ]
